### ISSUE TITLE
Treat check results as errors

### ISSUE THREAD

**Issue by Backs** [abuzhynsky/teamcity-pvs-studio-meta-runner#1]
How to mark all PVS checks of high priority as errors?

**Comment by abuzhynsky** [comment]
@Backs It's not implemented yet. Unfortunately I can't do it right now. I'll take a look in two weeks when I return home.

**Comment by Backs** [comment]
Ok, no problem.
I think, it's better to have an option, wich checks should be marked as errors.

**Comment by abuzhynsky** [comment]
@Backs Your feature request is finally implemented and can be found in release [1.1.0.0](https://github.com/abuzhynsky/teamcity-pvs-studio-meta-runner/releases/tag/v1.1.0.0). Sorry for delay.

**Comment by Backs** [comment]
Great work, thank you!
